# Generated by Django 4.1.6 on 2023-02-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandproduct',
            name='photo',
            field=models.ImageField(upload_to='photos/brand/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='photos/product/'),
        ),
    ]
